name: LDoc
on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - '**.lua'
jobs:
  sile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: 5.4
      - name: Generate docs with LDoc
        uses: lunarmodules/ldoc@v1
        with:
            args: --multimodule -a -d ./docs/reference/luadocs/. ./docs/reference/.
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Lua docs
          repository: ./docs/.
          branch: lua-doc
          create_branch: true

